### ISSUE TITLE
I got loss less than 0, the result of  function tf_2d_normal()  larger than 1 sometimes.

### ISSUE THREAD

**Issue by lyuwenyu** [vvanirudh/social-lstm-tf#1]
thx for u work, it helps me a lot.

I think here maybe need to do integral operation to get  probs.
model.py
```
tf_2d_normal(x_data, y_data, z_mux, z_muy, z_sx, z_sy, z_corr)
...
 -tf.log(tf.maximum(result0, epsilon))
```

**Comment by vvanirudh** [comment]
You are right. Instead of calculating the PDF (which could be greater than 1, resulting in a negative loss), I need to calculate the volume under the curve for a small area around the point. 

I will make the changes soon, but that shouldn't really affect the training. It just changes the loss values, I think.

**Comment by vvanirudh** [comment]
I just pushed some changes where I compute the volume under the curve for a rectangle of size 1e-3x1e-3. To do that I average the PDF values at the 4 corners and multiply it with the area of the rectangle to get the volume under the curve.

**Comment by vvanirudh** [comment]
Sadly, the model still performs poorly for more than one time-step prediction

**Comment by lyuwenyu** [comment]
Sorry,  I think about this point again.
In both this paper and Alex's work use Maximum-Likelihood model, Objective function should '\prod_{i=1}^n PDF' (here just one sample/point, so n equal 1), then `-log`.  In other word, the  result of objective function is not a probability. Therefore, negtive loss is ok.  oh... Here I am confuse, I'll check this view again.

Maybe, you original method is right.

**Comment by lyuwenyu** [comment]
To get probability maybe reasonable too.

**Comment by vvanirudh** [comment]
As I said, the value of the loss doesn't affect training in any way. Its just a metric to keep track of. A negative loss works fine as well. I made the change because negative loss looks out of place.

**Comment by lyuwenyu** [comment]
Got it. Thx a lot
