### ISSUE TITLE
Formula for the pixel co-ordinate normalization

### ISSUE THREAD

**Issue by avijit9** [vvanirudh/social-lstm-tf#12]
How did you normalize the co-ordinates? Can just do the following:

`(x/height, y/width)`

where height and width are the size of the image 

Thanks in advance.

**Comment by vvanirudh** [comment]
Check issue #11

**Comment by avijit99** [comment]
Yes, I have checked that issue. But after seeing your code in the data folder, I am getting confused. Can you please tell me the exact formula you used to normalize?

**Comment by vvanirudh** [comment]
The code for the interpolate files hasn't been added to the repo. But as I said in the other issue it is just:
`(2*x/height - 1, 2*y/width - 1)`

**Comment by avijit9** [comment]
Do you have the interpolation code? If yes, can you please add it to the repo? I just want to make sure everything is same between this data and my data for comparison purpose.
