### ISSUE TITLE
In UCY, Why divide the frame ID by 4,8,12 in getPixelCoordinates.m

### ISSUE THREAD

**Issue by erichhhhho** [vvanirudh/social-lstm-tf#13]
In three getPixelCoordinates.m, which preprocessed the data on students003.vsp, crowds_zara01.vsp, crowds_zara02.vsp, why divide the frame ID by 4,8,12 respectively? `floor(pixel_pos_frame_ped(1, :) / 8)`

**Comment by vvanirudh** [comment]
I don't remember exactly, but I am guessing it is because of different frame-rates in the videos
