### ISSUE TITLE
why seg_length=pred_length+obs_length in sample.py

### ISSUE THREAD

**Issue by xuhang96** [vvanirudh/social-lstm-tf#3]
Hi,
    data_loader = DataLoader(1, sample_args.pred_length + sample_args.obs_length, dataset, True)

why the seq_length=pred_length+obs_length not 1?

**Comment by vvanirudh** [comment]
That is just to load the data and create sequences of length (pred_length + obs_length) to test on.

Check the sample function in model.py to see how I pass seq_length=1 to the model at test time
