### ISSUE TITLE
In social-lstm,how do you achieve the "social"?

### ISSUE THREAD

**Issue by drawStar** [vvanirudh/social-lstm-tf#5]
Hi,I have a problem of your social-lstm codes in social_model.py.

I can't understand the function of getSocialTensor()。
how does this function achieve the pooling?

**Comment by vvanirudh** [comment]
We have pre-computed the social occupancy grids beforehand and use them to compute the social tensor (and thereby doing the social pooling operation). Note that pooling is essentially a tensor multiplication with a tensor with 1s and 0s. 

Check the code here: https://github.com/vvanirudh/social-lstm-tf/blob/master/social_lstm/social_model.py#L304 (the function `getSocialTensor` does the pooling in the form of a tensor multiplication)
