### ISSUE TITLE
Predicted trajectories are not being used to predict the next trajectories

### ISSUE THREAD

**Issue by avijit9** [vvanirudh/social-lstm-tf#6]
In the original paper, it is mentioned that during inference they use predicted trajectories in place of true trajectories. See the **Inference for path prediction** subsection. But the **social_sample.py** I get that it is using the true coordinates every time (line no 134-145).

**Comment by vvanirudh** [comment]
No. At prediction time, the code is using a sample from its own prediction at the previous time-step as input in the current time-step. Check the code here : https://github.com/vvanirudh/social-lstm-tf/blob/master/social_lstm/social_model.py#L380 (from line 380 onwards)
