### ISSUE TITLE
Social Pooling 

### ISSUE THREAD

**Issue by agrimgupta92** [vvanirudh/social-lstm-tf#7]
A call to BasicLSTMcell returns output_tensor, cell_state. ([ref](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/rnn_cell_impl.py#L414)) Here new_h is the output_tensor and new_state is the cell_state. However, in code I see you are using the output_tensor for social pooling. Shouldn't the cell_state be utilized for social pooling layer. 
Specifically, getSocialTensor should use input_states as argument in social_model.py. Can you please clarify?

**Comment by vvanirudh** [comment]
No, the cell state is a representation that LSTM uses inside its block to compute the hidden state (new_h) at each time-step. According to the paper, they use the hidden states of the LSTMs for social pooling and not the cell states. Hence, I used input_states as the argument for social pooling.
