### ISSUE TITLE
Similar existing repo ?

### ISSUE THREAD

**Issue by karttikeya** [vvanirudh/social-lstm-tf#8]
I am trying to use the SOCIAL LSTM model in chainer framework. But I am confused with the existence of a similar repo for Social LSTM : https://github.com/xuerenlv/social-lstm-tf . So, how do these repos differ, if at all they do? 

-Thanks for your time.

**Comment by vvanirudh** [comment]
The other repo is a fork of my repo at a previous commit. I made my repo private for a while so the fork information on that repo has been erased. I think I added validation during training since that fork in my repo. But, the core code is the same.
